import { beforeEach, describe, expect, it } from 'vitest';
import { store } from '../../src/store/InMemoryStore';
import { OrderService } from '../../src/services/OrderService';
import { CartService } from '../../src/services/CartService';
import { DiscountService } from '../../src/services/DiscountService';
import { AppError } from '../../src/errors/AppError';
import { config } from '../../src/config';

describe('OrderService', () => {
  let orderService: OrderService;
  let cartService: CartService;
  let discountService: DiscountService;
  const N = config.DISCOUNT_ORDER_INTERVAL;

  beforeEach(() => {
    store.seed();
    // Fresh instances per test — all share the reset store singleton
    cartService = new CartService();
    discountService = new DiscountService();
    orderService = new OrderService();
  });

  // ── checkout (core) ────────────────────────────────────────────────────────

  describe('checkout', () => {
    it('throws 404 when the cart does not exist', () => {
      expect(() => orderService.checkout('ghost-cart')).toThrowError(AppError);
    });

    it('throws 400 when the cart is empty', () => {
      cartService.addItem('cart-1', 'prod-1', 1);
      cartService.clearCart('cart-1');
      expect(() => orderService.checkout('cart-1')).toThrowError(AppError);
    });

    it('creates an order with correct subtotal and total (no discount)', () => {
      cartService.addItem('cart-1', 'prod-1', 2); // 299.99 x2 = 599.98
      const order = orderService.checkout('cart-1');
      expect(order.subtotal).toBe(599.98);
      expect(order.discountAmount).toBe(0);
      expect(order.total).toBe(599.98);
    });

    it('increments the global order counter', () => {
      cartService.addItem('cart-1', 'prod-1', 1);
      orderService.checkout('cart-1');
      expect(store.orderCounter).toBe(1);
    });

    it('persists the order to the store', () => {
      cartService.addItem('cart-1', 'prod-1', 1);
      const order = orderService.checkout('cart-1');
      expect(store.orders).toHaveLength(1);
      expect(store.orders[0].id).toBe(order.id);
    });

    it('clears the cart after a successful checkout', () => {
      cartService.addItem('cart-1', 'prod-1', 2);
      orderService.checkout('cart-1');
      const cart = cartService.getCart('cart-1');
      expect(cart.items).toHaveLength(0);
    });

    it('assigns sequential orderNumbers', () => {
      cartService.addItem('cart-1', 'prod-1', 1);
      cartService.addItem('cart-2', 'prod-2', 1);
      const order1 = orderService.checkout('cart-1');
      const order2 = orderService.checkout('cart-2');
      expect(order1.orderNumber).toBe(1);
      expect(order2.orderNumber).toBe(2);
    });

    it('snapshots cart items — changes after checkout do not affect the order', () => {
      cartService.addItem('cart-1', 'prod-1', 2);
      const order = orderService.checkout('cart-1');
      expect(order.items).toHaveLength(1);
      expect(order.items[0].quantity).toBe(2);
    });
  });

  // ── checkout with discount code ────────────────────────────────────────────
  //
  // Per spec, discount codes are generated by the ADMIN before the Nth order.
  // Tests here manually set up the store state (open window) and call
  // discountService.generateCode() directly — mirroring the admin endpoint flow.

  describe('checkout with discount code', () => {
    function openWindowForMilestone(c = 1) {
      // Put the order counter exactly at c*N - 1 (window open, order not yet placed)
      store.orderCounter = c * N - 1;
      store.discountMilestonesGenerated = c - 1;
    }

    it('applies a valid discount code and calculates the correct total', () => {
      // Admin generates code while the window is open (before the Nth order)
      openWindowForMilestone(1);
      const code = discountService.generateCode();

      // Customer places the Nth order and uses the code
      cartService.addItem('cart-1', 'prod-1', 1); // 299.99
      const order = orderService.checkout('cart-1', code.code);

      const expectedDiscount = parseFloat((299.99 * config.DISCOUNT_PERCENT / 100).toFixed(2));
      expect(order.discountAmount).toBe(expectedDiscount);
      expect(order.discountCode).toBe(code.code);
      expect(order.total).toBe(parseFloat((299.99 - expectedDiscount).toFixed(2)));
    });

    it('throws 400 when the discount code is invalid', () => {
      cartService.addItem('cart-1', 'prod-1', 1);
      expect(() => orderService.checkout('cart-1', 'INVALID-CODE')).toThrowError(AppError);
    });

    it('throws 400 when trying to reuse an already-used discount code', () => {
      openWindowForMilestone(1);
      const code = discountService.generateCode();

      // First use succeeds
      cartService.addItem('cart-a', 'prod-1', 1);
      orderService.checkout('cart-a', code.code);

      // Second use fails
      cartService.addItem('cart-b', 'prod-1', 1);
      expect(() => orderService.checkout('cart-b', code.code)).toThrowError(AppError);
    });

    it('marks the discount code as used after checkout', () => {
      openWindowForMilestone(1);
      const code = discountService.generateCode();

      cartService.addItem('cart-1', 'prod-1', 1);
      const order = orderService.checkout('cart-1', code.code);

      const updatedCode = store.discountCodes.get(code.code)!;
      expect(updatedCode.isUsed).toBe(true);
      expect(updatedCode.usedByOrderId).toBe(order.id);
    });
  });

  // ── no auto-generation after checkout ─────────────────────────────────────
  //
  // Verifies that checkout never auto-generates codes, even when N orders
  // have been placed. Code generation is admin-only.

  describe('no auto-generation on checkout', () => {
    it('does NOT generate a discount code when the Nth order is placed', () => {
      // Place exactly N orders
      for (let i = 0; i < N; i++) {
        cartService.addItem(`cart-${i}`, 'prod-2', 1);
        orderService.checkout(`cart-${i}`);
      }
      // No code should exist — only admin generates codes
      expect(store.discountCodes.size).toBe(0);
    });

    it('does NOT generate codes for any number of orders (including 2*N)', () => {
      for (let i = 0; i < 2 * N; i++) {
        cartService.addItem(`cart-${i}`, 'prod-2', 1);
        orderService.checkout(`cart-${i}`);
      }
      expect(store.discountCodes.size).toBe(0);
    });

    it('tracks order counter correctly for admin window checks', () => {
      // Place N-1 orders — the admin window for milestone 1 hasn't opened yet
      for (let i = 0; i < N - 1; i++) {
        cartService.addItem(`cart-${i}`, 'prod-2', 1);
        orderService.checkout(`cart-${i}`);
      }
      expect(store.orderCounter).toBe(N - 1);
      // Window is now open (N-1 orders placed) — admin CAN generate
      expect(discountService.shouldGenerateDiscount()).toBe(true);

      // Place the Nth order (without a code)
      cartService.addItem('cart-final', 'prod-2', 1);
      orderService.checkout('cart-final');
      expect(store.orderCounter).toBe(N);
      // Window is now closed — admin CANNOT generate (code wasn't prepared in time)
      expect(discountService.shouldGenerateDiscount()).toBe(false);
    });
  });
});
